#! python3
# renameDates.py - Renames filenames with American MM-DD-YYYY date format
# to European DD-MM-YYYY.

import shutil
import os
import re

#create a regex that matches files with the American date format
dataPattern = re.compile(r'''^(.*?) #all text before date
                            ((0|1)?\d)-  #one or two digits for the month
                            ((0|1|2|3)?\d)- #one or 2 digits for the day
                            ((19|20)?\d{2}) #four digits for the year
                            (.*?)$      #all text after that date
                            ''', re.VERBOSE)
for amerFilename in os.listdir('.'): #changes files in the current directory
    mo = dataPattern.search(amerFilename)

    if mo == None:
        continue

    beforePart = mo.group(1)
    monthPart = mo.group(2)
    daypart = mo.group(4)
    yearPart = mo.group(6)
    afterPart = mo.group(8)

    euroFileName = beforePart + daypart + '-' + monthPart + '-' +  yearPart + afterPart

    absWorkingDir = os.path.abspath('.')
    amerFilename = os.path.join(absWorkingDir, amerFilename)
    euroFileName = os.path.join(absWorkingDir, euroFileName)

    shutil.move(amerFilename, euroFileName)